### ISSUE TITLE
fstringify and black don't play well together

### ISSUE THREAD

**Issue by edreamleo** [jacktasia/fstringify#13]
After uninstalling black, `pip install black` yields:
```
ERROR: fstringify 0.1.6 has requirement black==18.9b0, but you'll have black 19.3b0 which is incompatible.
```
Afaik, this makes it difficult/impossible to use both fstringify and the latest version of black.

This is a fairly big deal, because the API of black keeps changing.

And I'm wondering whether this issue may be involved in #10.

**Comment by jacktasia** [comment]
I bumped the black version requirement for `0.1.14`. Thanks for opening all of these issues!

**Comment by edreamleo** [comment]
@jacktasia You're welcome.  I've fallen in love with python's f-strings, and fstringify has been very useful in the conversion.
